INSERT IGNORE INTO permissions (id, `key`, module, description) VALUES
  (UUID(), 'flowchart.run.view', 'officeperf', 'View workflow runs and tasks for other employees'),
  (UUID(), 'flowchart.run.create', 'officeperf', 'Start a new workflow run'),
  (UUID(), 'flowchart.task.assign', 'officeperf', 'Assign a flowchart task to an employee you do not directly manage'),
  (UUID(), 'flowchart.task.update', 'officeperf', 'Update the status of a flowchart task belonging to another employee'),
  (UUID(), 'checklist.template.view', 'officeperf', 'View checklist templates'),
  (UUID(), 'checklist.template.create', 'officeperf', 'Create checklist templates'),
  (UUID(), 'checklist.template.update', 'officeperf', 'Edit checklist templates and assignments'),
  (UUID(), 'checklist.template.delete', 'officeperf', 'Delete checklist templates'),
  (UUID(), 'checklist.instance.view', 'officeperf', 'View checklist completion for other employees'),
  (UUID(), 'delegation.task.view', 'officeperf', 'View delegated tasks for employees you do not directly manage'),
  (UUID(), 'delegation.task.create', 'officeperf', 'Delegate a task to an employee you do not directly manage'),
  (UUID(), 'delegation.task.update', 'officeperf', 'Update a delegated task belonging to another employee'),
  (UUID(), 'performance.dashboard.department.view', 'officeperf', 'View department-level performance dashboard'),
  (UUID(), 'performance.dashboard.company.view', 'officeperf', 'View company-wide (CEO) performance dashboard');
