CREATE TABLE IF NOT EXISTS machine_targets (
  id CHAR(36) PRIMARY KEY,
  machine_id CHAR(36) NOT NULL,
  size VARCHAR(100) NOT NULL,
  target DECIMAL(10, 2) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  FOREIGN KEY (machine_id) REFERENCES machines(id) ON DELETE CASCADE,
  UNIQUE KEY unique_machine_size (machine_id, size)
);

CREATE TABLE IF NOT EXISTS machine_efficiency_entries (
  id CHAR(36) PRIMARY KEY,
  department_id CHAR(36) NOT NULL,
  machine_id CHAR(36) NOT NULL,
  size VARCHAR(100) NOT NULL,
  target DECIMAL(10, 2) NOT NULL,
  achieved DECIMAL(10, 2) NOT NULL,
  manpower_count INT NOT NULL DEFAULT 1,
  efficiency DECIMAL(5, 2) NOT NULL,
  created_by CHAR(36) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE CASCADE,
  FOREIGN KEY (machine_id) REFERENCES machines(id) ON DELETE CASCADE,
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE
);
