CREATE TABLE IF NOT EXISTS master_hods (
  id CHAR(36) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE dpr_entries 
ADD COLUMN hod_id CHAR(36) NULL AFTER supervisor_id,
ADD CONSTRAINT dpr_entries_hod_fk FOREIGN KEY (hod_id) REFERENCES master_hods(id) ON DELETE SET NULL;
