CREATE TABLE IF NOT EXISTS issued_notices (
  id CHAR(36) PRIMARY KEY,
  employee_name VARCHAR(255) NOT NULL,
  department VARCHAR(255),
  notice_type VARCHAR(255) NOT NULL,
  category VARCHAR(255) NOT NULL,
  issue_date DATE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
