CREATE TABLE IF NOT EXISTS orders_in_hand (
  id VARCHAR(36) PRIMARY KEY,
  order_id VARCHAR(100) NOT NULL UNIQUE,
  order_date DATE NOT NULL,
  customer_name VARCHAR(255) NOT NULL,
  country VARCHAR(100),
  sales_executive VARCHAR(255) NOT NULL,
  marketplace ENUM('Etsy', 'Shopify', 'Wholesale', 'Amazon', 'Website'),
  po_number VARCHAR(100),
  no_of_products INT,
  total_qty INT,
  order_value DECIMAL(12,2),
  currency ENUM('USD', 'GBP', 'EUR', 'INR'),
  payment_status ENUM('Paid', 'Partial', 'Pending'),
  production_status ENUM('Pending', 'In Progress', 'Completed'),
  qc_status ENUM('Pending', 'Passed', 'Failed'),
  packing_status ENUM('Pending', 'Completed'),
  dispatch_status ENUM('Pending', 'Booked', 'Dispatched'),
  expected_dispatch_date DATE,
  expected_delivery DATE,
  priority ENUM('Low', 'Medium', 'High', 'Urgent'),
  delay_days INT,
  current_stage VARCHAR(255),
  overall_progress INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
