CREATE TABLE IF NOT EXISTS security_night_forms (
  id CHAR(36) PRIMARY KEY,
  guard_name VARCHAR(255) NOT NULL,
  shift_date DATE NOT NULL,
  gate_location VARCHAR(255) NULL,
  patrol_status VARCHAR(255) NOT NULL DEFAULT 'Normal',
  observations TEXT NULL,
  remarks TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS security_visitor_entries (
  id CHAR(36) PRIMARY KEY,
  visitor_name VARCHAR(255) NOT NULL,
  phone VARCHAR(50) NULL,
  company_name VARCHAR(255) NULL,
  person_to_meet VARCHAR(255) NULL,
  purpose VARCHAR(500) NULL,
  in_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  out_time DATETIME NULL,
  status ENUM('Checked-In', 'Checked-Out') NOT NULL DEFAULT 'Checked-In',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
