import { v4 as uuid } from "uuid";
import { pool } from "../../../../infrastructure/database/mysql/connection";
import { IBehaviourRepository } from "../../domain/repositories/IBehaviourRepository";
import { AnalyticsService } from "./AnalyticsService";
import { HealthService } from "./HealthService";
import { GeneratedInsight, InsightSeverity, PeriodType } from "../../domain/entities/Behaviour";
import { lastNPeriodKeys, dateRangeForPeriod } from "./periodUtils";

/**
 * A deterministic, rule-based Insights Engine - explicitly NOT an AI
 * integration. Every insight below is generated by a plain threshold
 * comparison against real computed data, with thresholds configurable via
 * `insight_rules` ("Everything configurable" per the spec).
 *
 * generateNarrativeSummary() is the clearly marked seam where a future
 * OpenAI (or similar) call would go, to turn this list of discrete findings
 * into flowing prose. It is currently a plain concatenation - no AI model
 * is called anywhere in this engine.
 */
export class InsightsEngineService {
  constructor(
    private readonly repo: IBehaviourRepository,
    private readonly analyticsService: AnalyticsService,
    private readonly healthService: HealthService
  ) {}

  private async record(ruleKey: string, severity: InsightSeverity, message: string, entityType: string | null, entityId: string | null, periodType: PeriodType, periodKey: string) {
    await this.repo.recordInsight({ id: uuid(), ruleKey, severity, message, entityType, entityId, periodType, periodKey });
  }

  private async checkProductivityDrop(threshold: number, periodType: PeriodType, periodKey: string) {
    const priorKey = lastNPeriodKeys(periodType, 2, periodType === "monthly" ? new Date(`${periodKey}-01`) : new Date(`${periodKey}-01-01`))[0];
    if (priorKey === periodKey) return;
    const current = dateRangeForPeriod(periodType, periodKey);
    const prior = dateRangeForPeriod(periodType, priorKey);

    const [rows] = await pool.query<any[]>(
      `SELECT fd.name,
         (SELECT SUM(actual_qty)/NULLIF(SUM(target_qty),0)*100 FROM factory_production_entries WHERE factory_department_id = fd.id AND deleted_at IS NULL AND entry_date BETWEEN ? AND ?) as currentAchievement,
         (SELECT SUM(actual_qty)/NULLIF(SUM(target_qty),0)*100 FROM factory_production_entries WHERE factory_department_id = fd.id AND deleted_at IS NULL AND entry_date BETWEEN ? AND ?) as priorAchievement
       FROM departments fd WHERE fd.deleted_at IS NULL`,
      [current.from, current.to, prior.from, prior.to]
    );
    for (const r of rows) {
      if (r.currentAchievement === null || r.priorAchievement === null) continue;
      const drop = Number(r.priorAchievement) - Number(r.currentAchievement);
      if (drop >= threshold) {
        await this.record("productivity_drop", "warning", `${r.name} productivity reduced by ${Math.round(drop * 10) / 10}%.`, "factory_department", r.name, periodType, periodKey);
      }
    }
  }

  private async checkMerchantFollowupsMissed(threshold: number, periodType: PeriodType, periodKey: string) {
    const { from, to } = dateRangeForPeriod(periodType, periodKey);
    const [rows] = await pool.query<any[]>(
      `SELECT e.full_name, COUNT(*) as missed
       FROM crm_lead_followups clf
       JOIN crm_leads cl ON cl.id = clf.lead_id
       JOIN employees e ON e.id = cl.assigned_merchant_id
       WHERE clf.on_time = 0 AND DATE(clf.completed_at) BETWEEN ? AND ?
       GROUP BY e.full_name HAVING missed >= ?`,
      [from, to, threshold]
    );
    for (const r of rows) {
      await this.record("merchant_followups_missed", "warning", `Merchant ${r.full_name} missed ${r.missed} follow-ups.`, "merchant", r.full_name, periodType, periodKey);
    }
  }

  private async checkDepartmentDeclining(threshold: number, periodType: PeriodType, periodKey: string) {
    const priorKey = lastNPeriodKeys(periodType, 2, periodType === "monthly" ? new Date(`${periodKey}-01`) : new Date(`${periodKey}-01-01`))[0];
    if (priorKey === periodKey) return;
    const current = await this.healthService.departmentHealth(periodType, periodKey);
    const prior = await this.healthService.departmentHealth(periodType, priorKey);
    const priorMap = new Map(prior.map((d) => [d.departmentName, d.averageIndex]));
    for (const dept of current) {
      const priorScore = priorMap.get(dept.departmentName);
      if (priorScore === undefined) continue;
      const drop = priorScore - dept.averageIndex;
      if (drop >= threshold) {
        await this.record("department_declining", "critical", `Department ${dept.departmentName} is declining (behaviour index down ${Math.round(drop * 10) / 10} points).`, "department", dept.departmentName, periodType, periodKey);
      }
    }
  }

  private async checkConsistencyImproved(threshold: number, periodType: PeriodType, periodKey: string) {
    const priorKey = lastNPeriodKeys(periodType, 2, periodType === "monthly" ? new Date(`${periodKey}-01`) : new Date(`${periodKey}-01-01`))[0];
    if (priorKey === periodKey) return;
    const currentFactory = await this.healthService.factoryHealth(periodType, periodKey);
    const priorFactory = await this.healthService.factoryHealth(periodType, priorKey);
    const priorMap = new Map(priorFactory.map((f) => [f.departmentName, f.onTimeRate]));
    for (const dept of currentFactory) {
      const priorRate = priorMap.get(dept.departmentName);
      if (priorRate === null || priorRate === undefined || dept.onTimeRate === null) continue;
      const improvement = dept.onTimeRate - priorRate;
      if (improvement >= threshold) {
        await this.record("consistency_improved", "info", `${dept.departmentName} consistency improved by ${Math.round(improvement * 10) / 10} points.`, "factory_department", dept.departmentName, periodType, periodKey);
      }
    }
  }

  private async checkRepeatDefaulters(threshold: number, periodType: PeriodType, periodKey: string) {
    const defaulters = await this.analyticsService.repeatDefaulters(periodType, periodKey, 3, Math.max(2, Math.round(threshold)));
    for (const d of defaulters) {
      await this.record("repeat_defaulter", "critical", `${d.employeeName} has been a bottom performer in ${d.occurrences} of the last ${d.periodsChecked} periods.`, "employee", d.employeeId, periodType, periodKey);
    }
  }

  async runInsights(periodType: PeriodType, periodKey: string): Promise<GeneratedInsight[]> {
    const rules = await this.repo.listInsightRules();
    const ruleMap = new Map(rules.map((r) => [r.ruleKey, r]));

    const productivityDrop = ruleMap.get("productivity_drop");
    if (productivityDrop?.enabled) await this.checkProductivityDrop(productivityDrop.thresholdValue, periodType, periodKey);

    const followupsMissed = ruleMap.get("merchant_followups_missed");
    if (followupsMissed?.enabled) await this.checkMerchantFollowupsMissed(followupsMissed.thresholdValue, periodType, periodKey);

    const departmentDeclining = ruleMap.get("department_declining");
    if (departmentDeclining?.enabled) await this.checkDepartmentDeclining(departmentDeclining.thresholdValue, periodType, periodKey);

    const consistencyImproved = ruleMap.get("consistency_improved");
    if (consistencyImproved?.enabled) await this.checkConsistencyImproved(consistencyImproved.thresholdValue, periodType, periodKey);

    const repeatDefaulter = ruleMap.get("repeat_defaulter");
    if (repeatDefaulter?.enabled) await this.checkRepeatDefaulters(repeatDefaulter.thresholdValue, periodType, periodKey);

    return this.repo.listInsights(periodType, periodKey);
  }

  listInsights(periodType: PeriodType, periodKey: string) {
    return this.repo.listInsights(periodType, periodKey);
  }

  /**
   * FUTURE AI HOOK - deliberately inert right now. This is where a call to
   * OpenAI (or any LLM) would eventually turn the list of discrete,
   * rule-based insights into a flowing executive narrative. Today it's a
   * plain-text concatenation; no external AI API is called anywhere in
   * this engine, per the explicit "do NOT integrate AI yet" instruction.
   */
  async generateNarrativeSummary(periodType: PeriodType, periodKey: string): Promise<string> {
    const insights = await this.repo.listInsights(periodType, periodKey);
    if (insights.length === 0) return "No notable findings for this period.";
    return insights.map((i) => `- ${i.message}`).join("\n");
  }
}
