import cron from "node-cron";
import { StandaloneChecklistService } from "./StandaloneChecklistService";
import { whatsappBot } from "../../../whatsapp/application/services/WhatsAppBotService";
import { pool } from "../../../../infrastructure/database/mysql/connection";

export class ChecklistReminderJob {
  private static instance: ChecklistReminderJob;
  private checklistService: StandaloneChecklistService;

  private constructor() {
    this.checklistService = new StandaloneChecklistService();
  }

  public static getInstance(): ChecklistReminderJob {
    if (!ChecklistReminderJob.instance) {
      ChecklistReminderJob.instance = new ChecklistReminderJob();
    }
    return ChecklistReminderJob.instance;
  }

  /**
   * Initializes the cron job to run every day at 9:00 AM.
   */
  public init() {
    // Schedule format: "Minute Hour DayOfMonth Month DayOfWeek"
    // "0 9 * * *" = 9:00 AM every day
    cron.schedule("0 9 * * *", async () => {
      console.log("[ChecklistReminderJob] Running daily checklist reminder check...");
      await this.runReminderProcess();
    }, {
      timezone: "Asia/Kolkata"
    });
    
    console.log("[ChecklistReminderJob] Scheduled to run daily at 9:00 AM.");
  }

  /**
   * Manual trigger for testing
   */
  public async runReminderProcess() {
    try {
      const allChecklists = await this.checklistService.getAllChecklists();
      const today = new Date();
      let sentCount = 0;

      // Normalize "today" to midnight for accurate date-only comparison
      const todayDateOnly = new Date(today.getFullYear(), today.getMonth(), today.getDate());

      for (const checklist of allChecklists) {
        if (!checklist.plannedDate || checklist.remindBeforeDays === undefined || checklist.remindBeforeDays === null) continue;

        const planned = new Date(checklist.plannedDate);
        const reminderDate = new Date(planned.getFullYear(), planned.getMonth(), planned.getDate());
        reminderDate.setDate(reminderDate.getDate() - checklist.remindBeforeDays);

        const shouldRemind = reminderDate.getTime() === todayDateOnly.getTime();
        if (shouldRemind) {
          // Send reminder to assign_to
          const [employeeRows] = await pool.query<any[]>(
            `SELECT phone, full_name FROM employees WHERE id = ?`,
            [checklist.assignTo]
          );

          if (employeeRows && employeeRows.length > 0) {
            const employee = employeeRows[0];
            if (employee.phone) {
              const message = `🔔 *Reminder*\nHi ${employee.full_name},\n\nYou have a checklist task scheduled for today.\n*Task:* ${checklist.taskName}\n\nPlease ensure it is completed on the portal.\n\n_Auto-generated by LII Nexus_`;
              await whatsappBot.sendMessage(employee.phone, message);
              sentCount++;
              console.log(`[ChecklistReminderJob] Sent reminder for checklist '${checklist.taskName}' to ${employee.full_name} (${employee.phone})`);
            } else {
               console.log(`[ChecklistReminderJob] User ${employee.full_name} has no phone number, skipping WhatsApp reminder.`);
            }
          }
        }
      }
      console.log(`[ChecklistReminderJob] Completed run. Sent ${sentCount} reminders.`);
    } catch (err) {
      console.error("[ChecklistReminderJob] Error running reminder process:", err);
    }
  }
}
